import { STORAGE_KEYS, DEFAULT_SETTINGS, sortAssignmentsByDueDate, getDeadlineWindow, buildReminderKey } from './utils.js';
import { fetchCurrentUser, fetchActiveCourses, fetchCourseAssignments, fetchSubmission } from './canvasApi.js';

const SYNC_ALARM='classpulse-sync-alarm';
chrome.runtime.onInstalled.addListener(async()=>{await ensureDefaults();chrome.alarms.create(SYNC_ALARM,{periodInMinutes:30});});
chrome.runtime.onStartup.addListener(async()=>{await ensureDefaults();chrome.alarms.create(SYNC_ALARM,{periodInMinutes:30});});
chrome.alarms.onAlarm.addListener(async a=>{if(a.name===SYNC_ALARM) await syncCanvasData(true);});
chrome.runtime.onMessage.addListener((m,_s,send)=>{if(m?.type==='SYNC_NOW'){syncCanvasData(true).then(r=>send({ok:true,result:r})).catch(e=>send({ok:false,error:e.message}));return true;} return false;});
async function ensureDefaults(){const d=await chrome.storage.local.get(STORAGE_KEYS.SETTINGS);if(!d[STORAGE_KEYS.SETTINGS]) await chrome.storage.local.set({[STORAGE_KEYS.SETTINGS]:DEFAULT_SETTINGS});}
async function syncCanvasData(triggerNotifications=false){const d=await chrome.storage.local.get([STORAGE_KEYS.AUTH,STORAGE_KEYS.SETTINGS]);const auth=d[STORAGE_KEYS.AUTH];const s=d[STORAGE_KEYS.SETTINGS]||DEFAULT_SETTINGS;const baseUrl=auth?.canvasBaseUrl||s.baseUrl;const token=auth?.accessToken||s.token;if(!baseUrl||!token) throw new Error('Connect Canvas or add manual token in Options.');
const cfg={baseUrl,token}; const user=await fetchCurrentUser(cfg); const courses=await fetchActiveCourses(cfg); const assignments=[];
for(const course of courses){const arr=await fetchCourseAssignments(course.id,cfg);for(const asn of arr){let sub=null;try{sub=await fetchSubmission(course.id,asn.id,cfg);}catch{} assignments.push({id:asn.id,courseId:course.id,courseName:course.name,courseColor:course.course_color||'#8fb3ff',name:asn.name,dueAt:asn.due_at,htmlUrl:asn.html_url,pointsPossible:asn.points_possible,submissionStatus:sub?.workflow_state||'unsubmitted'});}}
const sorted=sortAssignmentsByDueDate(assignments); await chrome.storage.local.set({[STORAGE_KEYS.USER]:user,[STORAGE_KEYS.ASSIGNMENTS]:sorted,[STORAGE_KEYS.LAST_SYNC_AT]:new Date().toISOString()}); if(triggerNotifications) await sendDueNotifications(sorted,s.reminderWindows||DEFAULT_SETTINGS.reminderWindows); return {assignmentsCount:sorted.length};}
async function sendDueNotifications(assignments,rem){const d=await chrome.storage.local.get(STORAGE_KEYS.NOTIFICATIONS_SENT);const sent=d[STORAGE_KEYS.NOTIFICATIONS_SENT]||{};for(const a of assignments){if(!a.dueAt||a.submissionStatus==='submitted') continue;const w=getDeadlineWindow(a.dueAt);const ok=(w==='due_today'&&rem.today)||(w==='due_tomorrow'&&rem.tomorrow)||(w==='due_in_3_days'&&rem.in3Days);if(!ok) continue;const k=buildReminderKey(a.id,w);if(sent[k]) continue;await chrome.notifications.create(`classpulse-${k}`,{type:'basic',iconUrl:chrome.runtime.getURL('icons/classpulse.svg'),title:`ClassPulse: ${a.name}`,message:`${a.courseName} is ${w.replaceAll('_',' ')}.`,priority:1});sent[k]=new Date().toISOString();}await chrome.storage.local.set({[STORAGE_KEYS.NOTIFICATIONS_SENT]:sent});}
