import { STORAGE_KEYS, formatDateTime, safeDate } from './utils.js';
const app=document.getElementById('app'); let state={};
init();
async function init(){state=await chrome.storage.local.get([STORAGE_KEYS.AUTH,STORAGE_KEYS.ASSIGNMENTS,STORAGE_KEYS.COURSES,STORAGE_KEYS.LAST_SYNC_AT]); if(!state.authState){app.innerHTML="<div class='card'><h1>ClassPulse</h1><p>Your Canvas command center</p><button id='go'>Connect Canvas</button></div>"; document.getElementById('go').onclick=()=>chrome.runtime.openOptionsPage(); return;} render();}
function render(){const a=state.assignments||[]; const courses=['All courses',...new Set(a.map(x=>x.courseName))]; app.innerHTML=`<header><h1>ClassPulse</h1><p>Your Canvas command center</p><span class='ok'>Connected</span><button id='sync'>Sync Now</button><div class='muted'>Last synced: ${state.lastSyncAt?new Date(state.lastSyncAt).toLocaleString():'Never'}</div></header><div class='card stats'><b>Due Today:</b>${count('today')} <b>This Week:</b>${count('week')} <b>Submitted:</b>${a.filter(x=>x.submitted).length} <b>Total Upcoming:</b>${a.filter(x=>!x.submitted).length}</div><div class='toolbar'><input id='q' placeholder='Search'><select id='course'>${courses.map(c=>`<option>${c}</option>`).join('')}</select></div><div class='tabs'><button data-f='today'>Today</button><button data-f='week'>This Week</button><button data-f='upcoming'>Upcoming</button><button data-f='submitted'>Submitted</button></div><div id='list'></div>`;
 document.getElementById('sync').onclick=sync; document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>draw(b.dataset.f)); document.getElementById('q').oninput=()=>draw('upcoming'); document.getElementById('course').onchange=()=>draw('upcoming'); draw('upcoming');}
function count(mode){const n=Date.now(),a=state.assignments||[]; if(mode==='today') return a.filter(x=>{const d=safeDate(x.dueAt);return d&&d.toDateString()===new Date().toDateString()&&!x.submitted;}).length; if(mode==='week') return a.filter(x=>{const d=safeDate(x.dueAt);return d&&d.getTime()-n<7*24*3600e3&&d.getTime()>=n&&!x.submitted;}).length; return 0;}
function draw(f){const q=document.getElementById('q').value.toLowerCase(); const c=document.getElementById('course').value; const now=Date.now(); let arr=(state.assignments||[]).filter(x=>(!q||x.name.toLowerCase().includes(q)||x.courseName.toLowerCase().includes(q))&&(c==='All courses'||x.courseName===c)); arr=arr.filter(x=>{const d=safeDate(x.dueAt); if(f==='submitted') return x.submitted; if(f==='today') return d&&d.toDateString()===new Date().toDateString()&&!x.submitted; if(f==='week') return d&&d.getTime()>=now&&d.getTime()<=now+7*24*3600e3&&!x.submitted; return !x.submitted;});
 const list=document.getElementById('list'); if(!arr.length){list.innerHTML="<div class='card'>You’re all caught up</div>"; return;} list.innerHTML=arr.map(x=>`<article class='card asn' style='border-left-color:${x.courseColor}'><div><b>${x.name}</b><span>${x.submitted?'Submitted':'Not submitted'}</span></div><div>${x.courseName}</div><div>${formatDateTime(x.dueAt)} · ${x.pointsPossible??'—'} pts</div><div><button class='open' data-url='${x.htmlUrl}'>Open</button></div></article>`).join(''); list.querySelectorAll('.open').forEach(b=>b.onclick=()=>chrome.tabs.create({url:b.dataset.url}));}
async function sync(){const b=document.getElementById('sync'); b.disabled=true; b.textContent='Syncing...'; const r=await chrome.runtime.sendMessage({type:'SYNC_NOW'}); b.disabled=false; b.textContent='Sync Now'; if(!r?.ok) alert(r?.error||'Sync failed'); await init();}
